/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import java.awt.Toolkit;
import javax.swing.JDialog;

/**
 *
 * @author student1
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
   // private final controller.Controller controller;
    
    public FMain() {
        initComponents();
        
       
//        setExtendedState(MAXIMIZED_BOTH);
        
        

        Toolkit tk = Toolkit.getDefaultToolkit();
        double x= tk.getScreenSize().getWidth();
        double y=tk.getScreenSize().getHeight();
        this.setSize((int)x, (int)y);
        
        
        setLocationRelativeTo(null);
        
      //  controller = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProduct = new javax.swing.JMenu();
        jMenuItemProductNew = new javax.swing.JMenuItem();
        jMenuItemProductSearch = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");

        jMenuProduct.setText("Product");

        jMenuItemProductNew.setText("New");
        jMenuItemProductNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductNewActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemProductNew);

        jMenuItemProductSearch.setText("Search");
        jMenuItemProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductSearchActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemProductSearch);

        jMenuBar1.add(jMenuProduct);

        jMenuAbout.setText("About");

        jMenuSoftware.setText("Sofware");
        jMenuAbout.add(jMenuSoftware);

        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProductNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductNewActionPerformed
        
        JDialog fProduct = new FProduct(this, true, ModeForm.ADD, null, null);
        fProduct.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItemProductNewActionPerformed

    private void jMenuItemProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductSearchActionPerformed
       
        JDialog fProductSearch = new FProductSearch(this, true);
        fProductSearch.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductSearchActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemProductNew;
    private javax.swing.JMenuItem jMenuItemProductSearch;
    private javax.swing.JMenu jMenuProduct;
    private javax.swing.JMenuItem jMenuSoftware;
    // End of variables declaration//GEN-END:variables
}
