/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import domain.Manufacturer;
import domain.Product;
import ui.components.table.model.ProductTableModel;
import java.awt.Frame;

import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Lazar-PC
 */
public class FProductSearch extends javax.swing.JDialog {
    //private final controller.Controller controller;
    /**
     * Creates new form FProductSearch
     */
        Frame parent;
//        JComboBox pom;
        
        
    public FProductSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
       // this.controller=controller;
        
        this.parent=parent;
        
        fillForm();
        
        jbtnDetails.setVisible(false);
        
        //selection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProducts = new javax.swing.JTable();
        jbtnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Manufacturer", "Price", "MeasurementUnit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblProducts.getTableHeader().setReorderingAllowed(false);
        jtblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProducts);
        if (jtblProducts.getColumnModel().getColumnCount() > 0) {
            jtblProducts.getColumnModel().getColumn(0).setResizable(false);
            jtblProducts.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtblProducts.getColumnModel().getColumn(1).setResizable(false);
            jtblProducts.getColumnModel().getColumn(1).setPreferredWidth(120);
            jtblProducts.getColumnModel().getColumn(2).setResizable(false);
            jtblProducts.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtblProducts.getColumnModel().getColumn(3).setResizable(false);
            jtblProducts.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtblProducts.getColumnModel().getColumn(4).setResizable(false);
            jtblProducts.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jbtnDetails.setText("Details");
        jbtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDetails))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetailsActionPerformed
        
        int row = jtblProducts.getSelectedRow();//uzimamo izabrani red iz tabele
      //  Product product = new Product(Long.MIN_VALUE, name, description, manufacturer, BigDecimal.ONE, MeasureUnit.PCS)
       // DefaultTableModel dtm = getModel();//uzimamo model da bi iz njega preuzeli podatke
        
//        Long id = (long)dtm.getValueAt(row, 0);
//        String name = (String)dtm.getValueAt(row, 1);
//        String desc =null;
//        Manufacturer manufacturer =  (Manufacturer)dtm.getValueAt(row, 2);
//        MeasureUnit measureUnit = (MeasureUnit)dtm.getValueAt(row, 4);
//        String s= (String)dtm.getValueAt(row, 3);
//        BigDecimal price = new BigDecimal(s.trim());
//        
//        Product product = new Product(id, name, desc, manufacturer, price, measureUnit);
//    
//        JDialog fproduct= new FProduct(parent, true, controller, ModeForm.VIEW, product);
//        fproduct.setVisible(true);
//        
        
        Long id = (long)(jtblProducts.getModel()).getValueAt(row, 0);
        
        Product product = controller.Controller.getInstance().searchProduct(id);
        
        JDialog fproduct= new FProduct(parent, true, ModeForm.VIEW, product, this);
        fproduct.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jbtnDetailsActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
//        jbtnDetails.setVisible(true);
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jtblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProductsMouseClicked
        // TODO add your handling code here:
        jbtnDetails.setVisible(true);
    }//GEN-LAST:event_jtblProductsMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetails;
    private javax.swing.JTable jtblProducts;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        List<Product> products = controller.Controller.getInstance().getProducts();
//        
        TableModel tm = new ProductTableModel(products);
        jtblProducts.setModel(tm);
        
//        DefaultTableModel dtm = getModel();
        

        //kako znamo da je model tabel izveden iz default table model?
        List<Manufacturer> manufacturers = controller.Controller.getInstance().getManufacturers();
//        JComboBox cb = new JComboBox(new DefaultComboBoxModel(manufacturers.toArray()));
////        pom=cb;
//        TableColumn tc = jtblProducts.getColumnModel().getColumn(2);
//        tc.setCellEditor(new DefaultCellEditor(cb));
        
        JComboBox jcb = new JComboBox();
        for (Manufacturer manufacturer : manufacturers) {
            jcb.addItem(manufacturer);
        }
        TableColumn tc2 = jtblProducts.getColumnModel().getColumn(2);
        tc2.setCellEditor(new DefaultCellEditor(jcb));



//        for (Product product : products) {
//            Object[] data = new Object[5];
//            data[0]= product.getId();
//            data[1]= product.getName();
//            data[2]= product.getManufacturer();
//            data[3]= product.getPrice();
//            data[4]= product.getMeasureUnit();
//            dtm.addRow(data);
//        }
        
//        int row = jtblProducts.getSelectedRow();
//        Product product = products.get(row);
//        int column = jtblProducts.getSelectedColumn();
//        switch(column){
//            case 2: product.setManufacturer((Manufacturer)cb.getSelectedItem()); break;
//            case 3: product.setPrice(new BigDecimal(dtm.getValueAt(row, column).toString())); break;
//        }
       
        
        
        
//        
    }

//    private DefaultTableModel getModel() {
//        return (DefaultTableModel) jtblProducts.getModel();
//    }
//    
//    public void refresTable(){
//        DefaultTableModel dtm= getModel();
//        
//        int numberOfRows= dtm.getRowCount();
//        for (int i = numberOfRows-1 ; i >=0 ; i--) {
//            dtm.removeRow(i); //Kako preko naseg modela?
//        }
//        
//        fillForm();
//        
//        
//    }
    
    public void selection(){
        
        ListSelectionModel model = jtblProducts.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                jbtnDetails.setVisible(true);
                 
            }
        });
    }
}
