/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Manufacturer;
import domain.MeasureUnit;
import domain.Product;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author student1
 */
public class FProduct extends javax.swing.JDialog {

    // private final Controller controller;
    private Product product;
    Frame parent;
    ModeForm mode;
    FProductSearch fps;

    /**
     * Creates new form FProduct
     */
    public FProduct(java.awt.Frame parent, boolean modal, ModeForm mode, Product product, FProductSearch fps) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        // this.controller=controller;
        this.product = product;
        this.parent = parent;
        this.mode = mode;
        this.fps = fps;

        fillForm();
        prepareForm(mode);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboMeasureUnit = new javax.swing.JComboBox<>();
        comboManufacturer = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jbtnSelectManufacturer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtProductError = new javax.swing.JTextArea();
        jbtnEnableChanges = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Product");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("Description");

        jLabel4.setText("Manufacturer");

        jLabel5.setText("Price");

        jLabel6.setText("MeasureUnit");

        jLabel1.setText("ID:");

        jtxtDescription.setColumns(20);
        jtxtDescription.setRows(5);
        jScrollPane1.setViewportView(jtxtDescription);

        jLabel2.setText("Name:");

        jbtnSelectManufacturer.setText("Select");
        jbtnSelectManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelectManufacturerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMeasureUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSelectManufacturer))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSelectManufacturer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(comboMeasureUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxtProductError.setColumns(20);
        jtxtProductError.setRows(5);
        jScrollPane2.setViewportView(jtxtProductError);

        jbtnEnableChanges.setText("Enable changes");
        jbtnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnableChangesActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(46, 46, 46)
                        .addComponent(jbtnEnableChanges)
                        .addGap(131, 131, 131)
                        .addComponent(jbtnUpdate)
                        .addGap(51, 51, 51)
                        .addComponent(btnSave)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel)
                        .addComponent(jbtnUpdate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(jbtnDelete))
                    .addComponent(jbtnEnableChanges))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Long id = Long.parseLong(txtId.getText().trim());
        String name = txtName.getText().trim();
        String desc = jtxtDescription.getText().trim();
        Manufacturer manufacturer = (Manufacturer) comboManufacturer.getSelectedItem();
        MeasureUnit measureUnit = (MeasureUnit) comboMeasureUnit.getSelectedItem();
        BigDecimal price = new BigDecimal(txtPrice.getText().trim());

        Product product = new Product(id, name, desc, manufacturer, price, measureUnit);
        Controller.getInstance().saveProduct(product);
        JOptionPane.showMessageDialog(this, "Product is saved ");

        /*
 Long id = Long.parseLong(txtId.getText().trim());
        String name = txtName.getText().trim();
        String description = jtxtDescription.getText().trim();
        Manufacturer manufacturer = (Manufacturer)comboManufacturer.getSelectedItem();
        BigDecimal price = new BigDecimal(txtPrice.getText().trim());
        MeasureUnit measurementUnit = (MeasureUnit)comboMeasureUnit.getSelectedItem();
        
        Product product = new Product(id, name, description, manufacturer, price, measurementUnit);
        controller.saveProduct(product);
        JOptionPane.showMessageDialog(this, "Product is saved");
         */
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jbtnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnableChangesActionPerformed
        prepareForm(ModeForm.UPDATE);
    }//GEN-LAST:event_jbtnEnableChangesActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        Long id = Long.parseLong(txtId.getText().trim());
        String name = txtName.getText().trim();
        String desc = jtxtDescription.getText().trim();
        Manufacturer manufacturer = (Manufacturer) comboManufacturer.getSelectedItem();
        MeasureUnit measureUnit = (MeasureUnit) comboMeasureUnit.getSelectedItem();
        BigDecimal price = new BigDecimal(txtPrice.getText().trim());

        Product product = Controller.getInstance().searchProduct(id);
        product.setName(name);
        product.setDescription(desc);
        product.setManufacturer(manufacturer);
        product.setPrice(price);
        product.setMeasureUnit(measureUnit);

        JOptionPane.showMessageDialog(parent, "Product is updated!");
        //fps.refresTable();

    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnSelectManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelectManufacturerActionPerformed
        //Pitaj sta se konkretno trazi ovde? kako da izgleda na formi?

        FManufacturerSelect fms = new FManufacturerSelect(parent, true, this);
        fms.setVisible(true);
    }//GEN-LAST:event_jbtnSelectManufacturerActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed

        int a = JOptionPane.showConfirmDialog(parent, "Delete product?");
        //0 yes
        //1 no
        //2 cancel
        //-1 exit
        if (a==0) {
            Long id = Long.parseLong(txtId.getText().trim());
            Controller.getInstance().removeProduct(id);
            JOptionPane.showMessageDialog(parent, "Product is deleted");
            prepareForm(ModeForm.VIEW);
            jbtnEnableChanges.setVisible(false);
            //fps.refresTable();
        } 
    }//GEN-LAST:event_jbtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> comboManufacturer;
    private javax.swing.JComboBox<Object> comboMeasureUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEnableChanges;
    private javax.swing.JButton jbtnSelectManufacturer;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextArea jtxtDescription;
    private javax.swing.JTextArea jtxtProductError;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        fillMeasurementUnits();
        fillManufacturers();
    }

    private void fillMeasurementUnits() {
        comboMeasureUnit.removeAllItems();

        comboMeasureUnit.addItem(MeasureUnit.KG);
        comboMeasureUnit.addItem(MeasureUnit.L);
        comboMeasureUnit.addItem(MeasureUnit.PCS);

    }

    private void fillManufacturers() {
        comboManufacturer.removeAllItems();

        List<Manufacturer> manufacturers = Controller.getInstance().getManufacturers();

        for (Manufacturer manufacturer : manufacturers) {
            comboManufacturer.addItem(manufacturer);
        }
    }

    private void prepareForm(ModeForm mode) {
        jtxtProductError.setEnabled(false);
        switch (mode) {
            case ADD:
                jbtnEnableChanges.setVisible(false);
                jbtnUpdate.setVisible(false);
                jbtnDelete.setVisible(false);
                break;
            case VIEW:
                jbtnEnableChanges.setVisible(true);
                jbtnUpdate.setVisible(false);
                btnSave.setVisible(false);
                jbtnDelete.setVisible(false);
                txtId.setText(product.getId().toString());
                txtName.setText(product.getName());
                txtPrice.setText(product.getPrice().toString());
                comboManufacturer.setSelectedItem(product.getManufacturer());
                comboMeasureUnit.setSelectedItem(product.getMeasureUnit());
                jtxtDescription.setText(product.getDescription());

                comboManufacturer.setEnabled(false);
                comboMeasureUnit.setEnabled(false);
                jbtnSelectManufacturer.setEnabled(false);
                txtId.setEditable(false);
                txtName.setEditable(false);
                txtPrice.setEditable(false);
                jtxtDescription.setEditable(false);
                break;
            case UPDATE:
                txtName.setEditable(true);
                txtPrice.setEditable(true);
                jtxtDescription.setEditable(true);
                comboManufacturer.setEnabled(true);
                comboMeasureUnit.setEnabled(true);
                jbtnSelectManufacturer.setEnabled(true);
                btnSave.setVisible(false);
                jbtnUpdate.setVisible(true);
                jbtnDelete.setVisible(true);

                break;

            default:;
        }
    }

    public void setComboManufacturer(Manufacturer manufacturer) {
        comboManufacturer.setSelectedItem(manufacturer);
    }
}
